// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdk-ODejjYu-u0irQKHDL41JFcYZlzmRw',
    appId: '1:109489990032:android:6fc388e67c21f635062b15',
    messagingSenderId: '109489990032',
    projectId: 'flutter-tut-mynotes',
    storageBucket: 'flutter-tut-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxRQ-XaHo-LMSiLEiOc-Aee-f5ayr6fEw',
    appId: '1:109489990032:ios:8b7870c444d635b7062b15',
    messagingSenderId: '109489990032',
    projectId: 'flutter-tut-mynotes',
    storageBucket: 'flutter-tut-mynotes.appspot.com',
    iosClientId: '109489990032-v63sujv7n92henqf8ik0mhsg76d2llrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter-tut-mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxRQ-XaHo-LMSiLEiOc-Aee-f5ayr6fEw',
    appId: '1:109489990032:ios:8b7870c444d635b7062b15',
    messagingSenderId: '109489990032',
    projectId: 'flutter-tut-mynotes',
    storageBucket: 'flutter-tut-mynotes.appspot.com',
    iosClientId: '109489990032-v63sujv7n92henqf8ik0mhsg76d2llrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter-tut-mynotes',
  );
}
